const Constants = {
    "DATE_FORMAT": "YYYY-MM-DD HH:MM:ss",
    "NAME": "NAME",
    "EXPERIENCE": "Experience",
    "TEST_SCORE": "Test Score",
    "TEST_STATUS": "Test Status",
    "L1_SCORE": "L1 Score",
    "L1_STATUS": "L1 Status",
    "GK_SCORE": "GK Score",
    "GK_STATUS": "GK Status",
    "FINAL_STATUS": "Final Status",
    "SENIORITY": "Seniority",
    "PAGINATION_NEXT_TEXT": "First",
    "PAGINATION_PREVIOUS_TEXT": "Back",
    "APP_TITLE": "Interview Scheduler",
    "EMPTY_TABLE_TEXT": "Sorry No Data",
    "BLANK_SCORE_TEXT": "Enter Score",
    "NA": "NA",
    "SELECTED": "Selected",
    "REJECTED": "Rejected",
    "SCHEDULE_L1": "Schedule L1",
    "FINISH_INTERVIEW": "Finish Interview",
    "SCHEDULE_GK": "Schedule GK",
    "STARTED_AT": "Started at",
    "SELECTED_IN": "Selected in",
    "REJECTED_IN": "Rejected in",
    "MINUTES": "mins",
    "COMPACT_DATE_FORMAT": "HH:mm:ss",
    "TEST_REJECTED": "Test Rejected",
    "L1_REJECTED": "L1 Rejected",
    "GK_REJECTED": "GK Rejected",
    "TEST_SELECTED": "Test Selected",
    "L1_SELECTED": "L1 Selected",
    "GK_SELECTED": "GK Selected",
    "L1_IN_PROGRESS": "L1 in Progress",
    "GK_IN_PROGRESS": "GK in Progress",
    "PASS_THRESHOLD": 3,
    "MAX_SCORE": 5,
    "MIN_SCORE": 1,
    "SIZE_PER_PAGE_LIST": [
        { text: '10', value: 10 },
        { text: '20', value: 20 },
        { text: '30', value: 30 },
        { text: '40', value: 40 },
        { text: '50', value: 50 }
    ],
    "DEFAULT_PAGE_SIZE": 10,
    "START_PAGE_INDEX": 1,
    "SPINNER_COLOR": 'rgba(192,192,192,0.3)'
}

export default Constants;